### ISSUE TITLE
Information board

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire-client#106]
I think it would be great to have some information about new functionalities or bug correction. A monthly synthesis would be fine.  
The standard way is to use a newsletter but I think there are already to many newsletter in the mailbox. The notification system of Inventaire.io could be used for it. It would just have a link to a page that resumes what has been done in the last 30 days. The page could be on Inventaire.io self, the wiki or the blog.

I like to try to update the information about the books that I have when there are new properties. Such a newsletter would be convenient for such a task and it shows also that the site evolves.

It would be also the occasion to tag new version (v2 is from June 2015)

**Comment by maxlath** [comment]
yes!

Different channels are used at the moment for updates on the project progresses:
- activity summaries: every 20 days (periodicity by default, but customizable by the user), an email is sent to give an overlook of pending notifications and new books in one's network, with which a short text can be added to inform everyone. Unfortunately, I couldn't maintain the rhythm and wrote only 3 of those: [1, 2](https://github.com/inventaire/inventaire/blob/i18n/archive/en.json#L2-L3), [3](https://github.com/inventaire/inventaire/blob/i18n/en.json#L56).
- [social networks](https://wiki.inventaire.io/wiki/Communication-channels?lang=en#social-networks), including the twitter account for developer news [@inventaire_dev](https://twitter.com/inventaire_dev)
- moving cards between the [roadmap](http://roadmap.inventaire.io) columns, but you got to go their to get the news, which presumably not that many people do.

I think straightening the existing channels, especially getting to write a text for the activity summary more regularly should be priority ＃1. Then, their is definitely room for a more complete sum up of things that happened around inventaire, at destination of fairly technical/expert users: we could take inspiration on [Wikidata weekly summary](https://www.wikidata.org/wiki/Wikidata:Status_updates/Next).

On versioning: I gave up on setting version numbers, I think it doesn't make sense for the project as a whole, given the iterative approach. Having [semantic versions](http://semver.org) could make sense for the [API](https://api.inventaire.io) though, but while we should definitely notify the community when there are breaking changes in the API, we don't have the resources to maintain several versions of the API running in parallel. Then we could have "marketing versions", that is, version bumps to signal to the larger (non-technical) community that a big feature was put online, but I can't think of any website doing it passed the big "X v2.0" announcement. Those big feature release should more systematically be announced by a [blog](http://blog.inventaire.io) post or a wiki article though.

**Comment by maxlath** [comment]
I forgot to mention one existing update channel: git commit messages and issues \o/
Those should be the primary place for changes documentation, to which we could link from the monthly(?) summary for further details.

By the way, when a commit message isn't clear enough or seem to miss context, feel free to ask for further details on the commit page.

**Comment by maxlath** [comment]
@thewholelifetolearn I started a [July 2017](https://wiki.inventaire.io/wiki/July-2017) summary, inspired by Wikidata's one, how those that look?
I created a weekly [time capsule](http://maxlath.eu/projects/time-capsule/) to try to keep in mind to update it ;)
