### ISSUE TITLE
improve barcode scan workflow for massive import

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire-client#112]
when scanning many books at once, the current workflow can be tedious: it could be an improvement to allow to first select visibility and transactions settings, and then to scan in bulk, without being interrupted as much as possible. The only interruption might then be when the edition can't be found (or should also those cases be all solved at the end?)

**Comment by almet** [comment]
Here are a few insights, that might or might not be good ideas, I'll let them here anyway.

*Disclaimer: I have no idea how everything is implemented neither in the frontend or backend.*

Currently, for every single book you need to select the audience and if you want to share / sell / list it. One way to make something more usable would be (in my opinion) to configure *first* how the import will be done for all the scanned items, and then scan them all.

That might happen in a queue on the server side, and if something bad happens (for instance if the book isn't found), it might be possible to list all the items that have a problem to the user in a subsequent page (or via an alert mechanism). One thing that might be problematic then is how to know which book it is (if the scan failed, then you cannot know!). One potential solution to this problem would be to display the book that was scanned just before and just after, in the UX.

**Comment by maxlath** [comment]
It has been possible to do mass scanning for some years now, closing
