### ISSUE TITLE
Search within a user inventory

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire-client#116]
With the new search bar, with would be very practical to search through our own library or even an other user. 
That would be a big improvement as for the moment the display of the library can't be filtered (author, series, title, ...)

**Comment by maxlath** [comment]
It use to be possible when loading the client meant loading the whole user inventory, but it was removed when we moved to lazy loading to enable larger inventories. It could be re-enabled aside from the filters (which are a work in progress) if it doesn't show to be too problematic: maybe items could be indexed in ElasticSearch too, from which we could request user-filtered item search? To be checked. The alternative being, building a list of all the titles in a given inventory, server-side or client-side, and filtering by text from there, but that can get quite expensive for large inventories

**Comment by maxlath** [comment]
Good news: there is now a server endpoint to do items search per user: [`/api/items?action=search&user=${userId}&search=${text}`](https://inventaire.io/api/items?action=search&user=6a65aa87e68e161650bf7741ad001249&search=crab)
So implementing a per-user inventory search is at hand! The only thing lacking is the UI: where should it be?

To add it to the global search bar, we would need a way to select the user first.

Having a search bar accessible somewhere near the inventory browser seems like a good association, maybe even in the inventory browser filter bar? The results should then probably respect the selected shelf and current filters: that could maybe be done on the client side, but it might be worth pushing some of those filters (especially the selected shelf) to the server request.

**Comment by jum-s** [comment]
if there is a search text, the client would request items with `/api/items?action=search&user=${userId}&search=${text}` and update the displayed  `inventory-view` ? 
`inventory-view`s are cached somewhere in the client, right ?

**Comment by maxlath** [comment]
done in #337 :tada: 

![Capture d’écran du 2022-09-08 19-15-03](https://user-images.githubusercontent.com/1596934/189184663-e927cdcf-0abb-4bc5-bbe2-dcafbfdee6e8.jpg)
