### ISSUE TITLE
Can't remove subtitle of a book

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire-client#117]
I think I have found a bug in the modification of an edition.  
It seems that it is not possible to remove a subtitle of a book. I tried to delete it or to save an empty field but it is not possible.

**Comment by maxlath** [comment]
thanks for reporting! for some reason, the delete event listener was commented-out fb82352

**Comment by maxlath** [comment]
the patch is online

**Comment by thewholelifetolearn** [comment]
That was fast! Well done 👍
