### ISSUE TITLE
t(...) is undefined in inventory browser

### ISSUE THREAD

**Issue by lucaswerkmeister** [inventaire/inventaire-client#121]
In https://inventaire.io/inventory/browser, when I filter by an author and then try to remove the filter, nothing happens, and the following error pops up in the console:

```
TypeError: t(...) is undefined https://inventaire.io/public/js/app.6bc9c44.js 16:14414 
Array [ "showItemsListByIds@/public/js/app.6bc9c44.js:16:14414", "displayFilteredItems@/public/js/app.6bc9c44.js:16:15589", "filterSelect@/public/js/app.6bc9c44.js:16:15304", "_triggerEventOnParentLayout@/public/js/vendor.9978983.js:7:3190", "triggerMethod@/public/js/vendor.9978983.js:7:2749", "resetOptions@/public/js/app.6bc9c44.js:15:28537", "toggleOptions@/public/js/app.6bc9c44.js:15:27184", "dispatch@/public/js/vendor.9978983.js:3:535", "add/g.handle@/public/js/vendor.9978983.js:2:30686", "" ]
TypeError: t(...) is undefined
```

It’s possible to change the author filter, and it’s also possible to add other filters and then remove the author filter. It seems that filters can fairly freely be added and removed, except that removing the last (only) filter doesn’t work, causing the above error.

Also, when I filter for books by @emulatingkat (same username on inventaire), who doesn’t have any items visible to me, the page breaks somewhat more permanently. The following error pops up in the console:

```
TypeError: t(...) is undefined https://inventaire.io/public/js/app.6bc9c44.js 16:14414 
Array [ "showItemsListByIds@/public/js/app.6bc9c44.js:16:14414", "displayFilteredItems@/public/js/app.6bc9c44.js:16:15628", "filterSelect@/public/js/app.6bc9c44.js:16:15304", "_triggerEventOnParentLayout@/public/js/vendor.9978983.js:7:3190", "triggerMethod@/public/js/vendor.9978983.js:7:2749", "selectOption@/public/js/app.6bc9c44.js:15:28285", "_triggerEventOnParentLayout@/public/js/vendor.9978983.js:7:3190", "triggerMethod@/public/js/vendor.9978983.js:7:2749", "select@/public/js/app.6bc9c44.js:15:30040", "dispatch@/public/js/vendor.9978983.js:3:535", … ]
TypeError: t(...) is undefined
```
(It’s similar to the above error, but the stack trace is different.) In this case, however, all other filter buttons are disabled, and I cannot edit the “owner” filter either. The only solution to that seems to be to reload the page.

**Comment by maxlath** [comment]
fixed by https://github.com/inventaire/inventaire-client/commit/832fd112e26d49587b74ff12c6c2d0617bbee7aa
