### ISSUE TITLE
add a "see user on the map" button on users profile

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire-client#129]
use case: when a unknown person requests a book after finding the owner on the map, there is no way to know where this person is without looking all around the map. Having a button to point where the user is would solve this issue

**Comment by maxlath** [comment]
solved by 1c31c2f

**Comment by jum-s** [comment]
for the record, it has been said by a tester i know that the map could be more visible than burried under `inventory` + `nearby` clicks.
any change of this nature include to have books or friends around the user position on the map. Which might not be the case for a lot users.
