### ISSUE TITLE
replace 'search' by 'search by' in query field

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire-client#131]
now that a query can be by tabs: subject work authors etc. 
it is more explicit to indicate it in the placeholder ` search by` to make an incentive for people to browse through the tabs and not in general, result would be more accurate and then users more satisfied.

**Comment by maxlath** [comment]
the issue I see with directly displaying `search by` is that it doesn't make sense if you don't see the search type selectors, which leads me to two possibilities:
- either we show `search` by default, and `search by ` only once the search input is focused and thus the type selectors visible
- or we make the search type selector visible by default, à la amazon.com (notice that they are not even using a placeholder):
![amazon_search](https://user-images.githubusercontent.com/1596934/33243326-3c12f8b8-d2e4-11e7-9b95-0f0a6fe84e69.png)

**Comment by jum-s** [comment]
first solution => fake, who reads a focused placehoder? 
second solution => amazon can offer the luxury to not describe what elements are for, not us. 

We are not leboncoin or google, we intend to have some structured data, and help user using this structure. Encouraging using tabs is the best way to do that. 

Since this great feature that is to search by type is available. its time to move on. Let people use it for good : 
displaying 'search by' directly makes sure people can use the tabs, 
if its simply 'search' people are making up their idea, then click and find out they can actually search by tabs.. counter productive,

**Comment by jum-s** [comment]
a11y audit pointed to have a more proeminent "serach" display han only the placeholder, this issue becomes irrelevant
