### ISSUE TITLE
Notification messages

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire-client#134]
when i click on a notification "accepted request", 
it links to the user profile
it would ease navigation to reference the request itself 
ie. `./transaction/6e244c2e6ad598b5ef7f62a7e4000e48` 

like it is the case when a comment is posted linking to an item `./items/5bb3931277d7358580a8aa2658031475`

![](https://user-images.githubusercontent.com/5363918/33716511-c5fb83cc-db56-11e7-9748-935b546937d7.png)

**Comment by maxlath** [comment]
no, the request here is a friendship request, transactions request notifications don't appear in the notifications but in the transactions manager (`/transactions`)

but the message could maybe make it more explicit that it's about a friendship request
