### ISSUE TITLE
placeholder when creating edition

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire-client#135]
when i want to add an edition from an existing work. 
i have to re-write the title name of the work. 
by default the title of the work should be the title of the edition (as a placeholder before creation)
![](https://user-images.githubusercontent.com/5363918/33719179-39a5853a-db60-11e7-853f-60709bae20b6.png)

**Comment by maxlath** [comment]
yes, that would definitely be a plus to prefill the title input, but without having it saved, like this:
![selection_002](https://user-images.githubusercontent.com/1596934/33721585-c7ca2ad0-db67-11e7-9372-c6ec64e90c06.png) (screenshot from [a work being created with a suggested title](https://inventaire.io/entity/new?type=work&label=Le%20Prince))

**Comment by jum-s** [comment]
done with svelte rewrite
