### ISSUE TITLE
Length of username using Persona signin

### ISSUE THREAD

**Issue by GDoukhan** [inventaire/inventaire-client#14]
Using Persona signin your username is usually your mail. 
So in this case, 20 characters for the username can be too short.

**Comment by maxlath** [comment]
Hi GDoukhan, welcome and thank you for posting an issue!
Actually, Inventaire needs a username AND an email, so the signup form asks for a username, distinct from the email, before redirecting to Persona's own signup form. Do you think there should be a tip to make it clearer?

**Comment by GDoukhan** [comment]
actually I had the problem creating a persona account.
I just tried again unlogging/signing up with the yet created persona
account and that's ok. I think that's because persona doesn't seem to
directly make the link at the end of the creation process with inventaire.io
.


Guillaume

2015-06-29 23:32 GMT+02:00 maxlath <notifications@github.com>:

**Comment by maxlath** [comment]
It should redirect from either it's own website - if you already have a Persona account - or from the confirmation email it sends you. Can be re-opened if this isnt the case
