### ISSUE TITLE
Title of books not readable on mobile when importing through batch

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire-client#147]
I tried this morning the new importer scan batch. It is really great! It is easier and faster to import.  
I had an odd behaviour: on the first try, one book wasn't displayed (or found) but when I tried the second time it was in the list.

But more important, this issue is regarding the display of the titles and authors in the batch list. As it can be seen on the screenshot, it is impossible to read the text. The screenshot was taken on my mobile phone in portrait mode. In landscape mode, this issue doesn't happen.
![screenshot_2018-04-17-07-42-29](https://user-images.githubusercontent.com/823564/38851342-ad737ece-4215-11e8-95cf-f80ab449183d.png)

**Comment by thewholelifetolearn** [comment]
For importing books, I use Chrome because when I used Firefox it opened a new window after each scan. I will let you know if this issue occurs on Firefox too on the next import.

**Comment by thewholelifetolearn** [comment]
First I tried with the built-in scanner of Firefox but it didn't work (black screen), so then I used an external scanner (Barcode scanner).  
But since I tried, there are some updates that have been done. It may work nicely now

**Comment by thewholelifetolearn** [comment]
I couldn't reproduce the issue on Firefox. The import with the internal scanner doesn't work on my phone. I will create a new issue for this problem so that this one stays clean

**Comment by maxlath** [comment]
thanks, which versions of Chrome and Firefox you're using?

**Comment by thewholelifetolearn** [comment]
So I use Chrome 65.0.3325.109 and Firefox 59.0.2 on Android 6.0.1

**Comment by maxlath** [comment]
@thewholelifetolearn the patch is now online, could you check if it does fix the issue?

**Comment by thewholelifetolearn** [comment]
I imported books this morning and the display was fine. I managed to read all the informations :+1:
