### ISSUE TITLE
Cannot import through internal scanner with Firefox

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire-client#148]
As the title mentions it, I cannot scan my books with the scanner of Firefox. Each time I want to scan, Firefox pops up a windows to allow him to use the rear camera. After that, I have a black scanner window trying to load. I can wait as long as I wish, the camera doesn't show up.  
See screenshot for display: 
![screenshot_2018-04-18-07-49-01](https://user-images.githubusercontent.com/823564/38913879-412a1840-42dd-11e8-9d1e-909f33d2bc39.png)

But it works if I use an external scanner like Barcode scanner. But then, I can only import one by one.

**Comment by maxlath** [comment]
sorry for the absence of response, do you still encounter this problem?

**Comment by thewholelifetolearn** [comment]
No problem. Yes, the problem is resolved. I forgot to close to issue.
