### ISSUE TITLE
make the item delete button clearer

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire-client#157]
[@thewholelifetolearn comment](https://github.com/inventaire/inventaire-client/issues/156#issuecomment-418810431):

> The display of those buttons aren't the best. I didn't search them at those location. I was looking for it on the edition page.

Having a "remove from my inventory" button could make sense. This should be part of a larger attempt to make intents clearer, see #130

>You should also precise that it deletes one edition from the inventory

**Comment by jum-s** [comment]
can this issue be considered solved ?  
reminder of current delete button status:
![2020-12-28_21-21](https://user-images.githubusercontent.com/5363918/103241173-535ddd00-494a-11eb-8439-95583d2e2f46.png)

honestly im not sure this delete button is visible enough, i would be for a "delete" text written in black next to the trash icon

**Comment by jum-s** [comment]
maybe @thewholelifetolearn have an opinion ?

**Comment by thewholelifetolearn** [comment]
As you say @jum-s , I would rather add in plain text "delete". There is enough space to put this word. It could be only the icon when displayed on a mobile.

**Comment by maxlath** [comment]
done in #271
