### ISSUE TITLE
invalid isbns show progress forever

### ISSUE THREAD

**Issue by niccokunzmann** [inventaire/inventaire-client#164]
If I enter a list of invalid ISBNs, the progess is shown forever.
I suppose nothing - no response comes for no ISBNs.

How to reproduce:

1. Open https://inventaire.io/add/import
2. then, I insert something into "1/ Import from a list of ISBNs" such as `ajlkjfdsajf ajfdkjds `
3. Then, I click on find ISBNs
4. observe closely and with due patience how the circle rotates while no progress is to be seen.

For consistency, I would expect a "0/0" text to appear

To close this: also test uploading a file with this content and report an issue.

**Comment by maxlath** [comment]
fixed by #312
