### ISSUE TITLE
Importing a book that has a title but not author is impossible

### ISSUE THREAD

**Issue by axelsimon** [inventaire/inventaire-client#179]
I tried to import a book (from the barcode scanner, but it's the same result entering its ISBN) which was recognised but for which there was only a title, but no author.
This is the page: https://inventaire.io/add/import

The book was added to the list of books to import, with a warning about the empty author.
However, there was no option to correct the author, the import would not go any further without the author and the import process was blocked there.

I eventually found the book, edited it to add the author, and then imported it successfully.

Suggestion: make it possible to edit / add missing fields during import.

**Comment by maxlath** [comment]
we received an email with a similar issue:
![image](https://user-images.githubusercontent.com/1596934/60977376-a6476d00-a32f-11e9-8706-78f498695c12.png)

**Comment by maxlath** [comment]
This issue is likely to have been resolved by 412b483, which is now online. Please re-open it if the error occurs again
