### ISSUE TITLE
Enable Merging Records by Users

### ISSUE THREAD

**Issue by Alamantus** [inventaire/inventaire-client#182]
Since Inventaire has so many duplicate records from import processes and other things, I believe that there should be a process to allow users to either merge _(with lots of confirmation that they know for 100% certain the records are the same)_ OR make it easy to submit "merge requests" to admins in a similar way to the "Report an Error" button.

I think that having this feature or something like it available to users will help streamline the process of cleaning up the database a lot.

**Comment by maxlath** [comment]
merged this issue with https://github.com/inventaire/inventaire/issues/91
