### ISSUE TITLE
[item view] align remove button

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire-client#191]
Delete item button is not aligned with other elements in the view, making it harder to see

![Sélection_010](https://user-images.githubusercontent.com/5363918/72176309-064dc780-33d6-11ea-8d72-c564208f8ea2.jpg)

 A better view woould align it with the rest of the elements, such as : 

![Sélection_009](https://user-images.githubusercontent.com/5363918/72176366-1fef0f00-33d6-11ea-8ee9-07d9008f2a6e.jpg)

**Comment by maxlath** [comment]
fixed by #192
