### ISSUE TITLE
Mobile menu broken in blink browsers

### ISSUE THREAD

**Issue by Abbe98** [inventaire/inventaire-client#22]
Opera Beta/Firefox Developer Edition:

![screenshot](https://cloud.githubusercontent.com/assets/2631719/9026131/c5eb9016-3923-11e5-8865-a410c1ad1bb3.png)

**Comment by Abbe98** [comment]
Seams to work in Chrome for Android.

**Comment by Abbe98** [comment]
This is gone, have no clue what the issue was...

**Comment by Abbe98** [comment]
Removing all IndexedDB content and visiting `https://inventaire.io/inventory` trigged the issue again.

**Comment by maxlath** [comment]
this is weird, how could IndexedDB be related to a css bug??

**Comment by Abbe98** [comment]
I have no idea, might be something else, will investigate further when I
get the time.

**Comment by maxlath** [comment]
obsolete issue: the menu got a major update since then
