### ISSUE TITLE
Item popup should be closed when login is required

### ISSUE THREAD

**Issue by iootaa** [inventaire/inventaire-client#221]
**How to reproduce?**

- Logout if you are connected and open an item. For example https://inventaire.io/entity/wd:Q393018
- Select the name of a random user lending the book. For example https://inventaire.io/items/6691f5e8d2b9b22d24a2e4c08605ff7f
- Click on `Send request`

See? The item popup hides the login form. It's at least the case with the following environement: Debian Buster + Tor Browser 9.5.4 (based on Mozilla Firefox 68.12.0esr)

Thank you, Cheers

**Comment by maxlath** [comment]
thanks for reporting! I pushed a patch 9f2d237 that should solve that, and that is now online: can you confirm it works as expected?

**Comment by iootaa** [comment]
Fixed, it's working fine now. Thank you
