### ISSUE TITLE
Enable to custom webpack/bundle config

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire-client#241]
Especially in relation with a custom server config, for example the  `proxy` key in `bundle/dev_server.cjs` could look like :

```
  proxy: {
    '/api': 'http://localhost:3009',
    '/public': 'http://localhost:3009',
    '/img': 'http://localhost:3009',
  },
```

possible implementation: place `bundle/dev_server.cjs` in `.gitignore` and create a default template

**Comment by maxlath** [comment]
done in #242
