### ISSUE TITLE
create shelves from importers

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire-client#253]
When someone use the external sites importers, it could create new shelves from the csv given.

i would leave the attempt to resolve on existing shelves, for a future version

We could start by goodread since it was mentioned by [arkhi](https://mamot.fr/@arkhi/105486197441627896)

**Comment by jum-s** [comment]
I am afraid importing shelves from an import file will be quite some work considering the strict schema that candidate items need to fit into
A simpler alternative would be to add the shelves menu already developed for other "add items options"
current view : 
![2021-01-19_17-57](https://user-images.githubusercontent.com/5363918/105067614-c35a1180-5a77-11eb-86e8-59854112995c.png)

other import ways :
![2021-01-19_17-58](https://user-images.githubusercontent.com/5363918/105067707-e389d080-5a77-11eb-88bd-fee0df16a645.png)

this would be trivial and allow a user to customize their csv into multiples files (one per shelf) before importing them

**Comment by arkhi** [comment]
Hello…

I don’t know the code nor the logic behind Inventaire so I don’t understand its inner complexity. My understanding is the following could be done:

1. _Get all arrays of shelves in the export file_ (one array of shelves per book, from what I saw in the csv I have);
1. _Merge those arrays together_ (unique names);
1. _From the resulting merge, unless a shelf with the same name already exists in the user shelves, add all shelves to the user shelves_;
1. _Assign each book to its related shelves_.

I can only mention I doubt users, unless they’re the computer‑nerd **and** book‑nerd types, would spend time curating their exports before importing them. That being written, it won’t hurt to implement the feature it if it’s trivial. :)

**Comment by jum-s** [comment]
We are closer as ever to solve this issue :) 
Your description of the possible implementation @arkhi is quite automatic. Maybe it would be nice for the user to let them choose which "imported shelf" shall be added to which "inventaire shelf".

Proposition: if some "importer shelf" are found, display a checkbox : `Would you like to import your [insert website name]'s shelves too ?`. When checked, a select menu would be display an  "imported shelf" and then a checkbox for each inventaire shelf
something like:

Add [importer shelf name] to the following shelves

- [ ] an inventaire shelf
- [ ] another inventaire shelf
- [ ] create a new shelf with title: **[importer shelf name]**

additional optional feature: default `checkbox: true`  if importer shelf and inventaire shelf have same name

**Comment by jum-s** [comment]
this is now in production :tada: 
ping @arkhi
