### ISSUE TITLE
author layout: display editions translated, pre and postfaced

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire-client#260]
We allow to set values for the following properties, but don't display the relation
* [translator](https://wikidata.org/entity/P655)
* [preface author](https://wikidata.org/entity/P2679)
* [postface author](https://wikidata.org/entity/P2680)

Those could be displayed on the author layout

This is important for not having "empty"/unrelated authors deleted by mistake, just because their contribution are not visible

**Comment by jum-s** [comment]
Relative entities lists does provide this information now:

* [translator](https://inventaire.io/entity/wd:Q120504899)
* [preface author](https://inventaire.io/entity/wd:Q7350708)
* [postface author](https://inventaire.io/entity/isbn:9782366244861)
