### ISSUE TITLE
linking to Gutenberg resources

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire-client#27]
there is a Wikidata property for [Project Gutenberg author ID](https://www.wikidata.org/wiki/Property:P1938) than can be used to build gutenberg.org urls such as [https://www.gutenberg.org/ebooks/author/85](https://www.gutenberg.org/ebooks/author/85).
Unfortuatly, the project doesn't have an API, making it hard to know the content you can expect on the other side of the link

**Comment by maxlath** [comment]
poke @frimelle

**Comment by maxlath** [comment]
integration done:
* showing Project Gutenberg author ID (P1938) in [author_claims](https://github.com/inventaire/inventaire-client/blob/master/app/modules/entities/views/templates/author_claims.hbs)
* showing Project Gutenberg ebook ID (P2034) in [book_claims](https://github.com/inventaire/inventaire-client/blob/master/app/modules/entities/views/templates/book_claims.hbs)

**Comment by frimelle** [comment]
Sorry, saw it too late since I didn't know what notification means what :D Now I figured and am pokable though ;)
And yay for doing this \o/
