### ISSUE TITLE
isbn pattern do not fit valid isbn

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire-client#282]
Looks like the valid isbn 978-2-918-490-11-1 ([editor's page](https://wildproject.org/livres/le-petit-livre-des-grands-barbus)) do not fit the [isbn extractor](https://github.com/inventaire/inventaire-client/blob/master/app/modules/inventory/lib/import/extract_isbns.js#L2) of the importer.

**Comment by jum-s** [comment]
updating the regex from 13 to 14 will do.

`const isbnPattern = /(97(8|9))?[\d-]{9,14}([\dX])/g`

**Comment by maxlath** [comment]
the ISBN on the editor's page is actually invalid, [an ISBN-13 only has 5 parts](https://en.wikipedia.org/wiki/International_Standard_Book_Number#/media/File:ISBN_Details.svg), but the isbn extractor isn't there to validate but to extract, so if that mistake happens, extending the regex to cover it makes sense. But please add a comment to explain how we got there

**Comment by maxlath** [comment]
[the `978-2-918490` editor prefix is confirmed by the afnil](https://www.afnil.org/afnil_editeurs/763141/), confirming that the valid ISBN is `978-2-918490-11-1`

**Comment by jum-s** [comment]
done with `18a07f209`
