### ISSUE TITLE
Bullet point is displayed in edition list

### ISSUE THREAD

**Issue by AutomCoding** [inventaire/inventaire-client#294]
The bullet point by this list item is rendered (also, the `li` tag is not nested in an `ol` or `ul`):

https://inventaire.io/entity/wdt:P2679-inv:08b42c3bb8fc7a30912cbb535e1d5a65
![Screenshot_20211103_132103](https://user-images.githubusercontent.com/40275136/140060472-3749db3c-e6c6-468e-9b66-1541210077e2.png)

**Comment by maxlath** [comment]
thanks for reporting! should now be fixed

**Comment by AutomCoding** [comment]
Seems to have fixed it, thanks!
