### ISSUE TITLE
Can't merge works using new dropdown

### ISSUE THREAD

**Issue by AutomCoding** [inventaire/inventaire-client#320]
I get the error message "invalid entity type" when trying to merge works via the new dropdown menu. I have not tried with other entity types yet.

1. Go to [this work](https://inventaire.io/entity/inv:a9e4cca0a45dcac6ffbb50a0b85cfbc0)
2. Click edit pencil
3. Click cogwheel --> merge
4. Type "inv:fc498b96cf319a9c5e1fa92091da51aa" in the search box
5. Now, try with the title of the other work, "Assassination classroom 1"

Both step 4 and 5 result in the same error, mentioned above.

**Comment by maxlath** [comment]
Thanks for reporting! That now fixed (patch: 0989fd1)
