### ISSUE TITLE
Translation key displayed

### ISSUE THREAD

**Issue by AutomCoding** [inventaire/inventaire-client#329]
The translation key "shelves_importer_description" get rendered to user instead of a corresponding text. This is displayed when adding books to inventory by isbn list. Issue is the same regardless of selected interface language.

[select_shelves.svelte](https://github.com/inventaire/inventaire-client/blob/master/app/modules/inventory/components/importer/select_shelves.svelte)

![isbn-import](https://user-images.githubusercontent.com/40275136/178025293-aa3988c8-7a4a-454c-94d3-392c992686f6.png)

**Comment by maxlath** [comment]
I [added the missing i18n keys](https://github.com/inventaire/inventaire-i18n/commit/399406d5f4403ec38f8dd9ba76a0d3831fc7a36a#diff-6c90e41a93428b20a2f40195dbe9c122fed4542dbe4111ffcf4600ea00ec8362), and updated the build, so that should now be fixed.
Thanks again for reporting! :D
