### ISSUE TITLE
Admins cannot merge editions

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire-client#350]
It sometimes occur to have [an edition](https://inventaire.io/entity/inv:754842d442485f28a055beaeef387771) that could reasonably be merged into another edition.
It could be nice to give dataadmin, a section at the bottom of the edition layout, to be able to merge edition

Criterias for merge; 
- from edition dont have any isbn
- to and from editions have the same work

What it could look like:
![2022-10-08_12-34](https://user-images.githubusercontent.com/5363918/194703257-3f5c59b2-2574-44b1-99d6-361b07f1eafe.png)

**Comment by maxlath** [comment]
The menu on `/entity/${uri}/edit` already offers a way to merge an edition entity via the `/entity/merge?from=${uri}` layout, but that layout could be made nicer for the edition case, for instance by suggesting other editions from the same work that could effectively be merged (that is, without both editions having an ISBN)?

**Comment by jum-s** [comment]
There is indeed a way to merge edition, i was not familiar enough with the edit menu yet.
