### ISSUE TITLE
add internal barcode scanner capabilities

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire-client#37]
it should be possible using [quagga.js](https://github.com/serratus/quaggaJS) but I can't make it work: 

the `onDetected` callback is never called

``` coffeescript
config =
  inputStream :
    name : "Live",
    type : "LiveStream"
    constraints:
      width: 640,
      height: 480,
      facing: "environment" # or user
  debug: true
  decoder :
    readers : [ 'code_128_reader', 'ean_reader', 'codabar_reader' ]
  locator:
    halfSample: true,
    patchSize: "medium",

module.exports = ->
  console.log 'STARTING'
  Quagga.init config, (err)->
    if err? then return console.log err, 'init err'
    console.log 'Initialization finished. Ready to start'
    Quagga.start()

  Quagga.onDetected (data)-> console.log data, 'onDetected'
```

**Comment by roukydesbois** [comment]
I guess my issue is linked to this one: running on iOS 10.2.1 (iPad and iPhone) in both Firefox and Safari, I cannot use the barcode scanning functionality.
And unfortunately I cannot really help you with making quagga work ;)

**Comment by maxlath** [comment]
@roukydesbois well, this issue was actually solved by 1eb7129 but I forgot to update it, sorry.
Could you give more details on the issue your encounter? At what point is it failing? (screenshot welcome)

**Comment by roukydesbois** [comment]
Thanks @maxlath for the swift answer!
When I go to /add/scan, I get this error in Firefox and Safari on both iPhone and iPad:

![2017-02-11 18-07-08 1215](https://cloud.githubusercontent.com/assets/11874580/22856053/83e0d92c-f08a-11e6-970d-b7592996cdec.png)

**Comment by maxlath** [comment]
thanks for the screenshot! After some tests on a friend's ipad, it seems that iOS Firefox can't use `navigator.mediaDevices.enumerateDevices`, thus [has_video_input.coffee#L9](https://github.com/inventaire/inventaire-client/blob/e9023daa55fe3116b7a061fc380b472e9e8cd49c/app/lib) returning an error of the kind `Error: Device enumeration not supported.`

There are some polyfills that could help work around it but I couldn't make it work:
- [adapter.js](https://github.com/webrtc/adapter)
- [enumerate-devices-shim](https://www.npmjs.com/package/enumerate-devices-shim)

**Comment by maxlath** [comment]
damned. `navigator.mediaDevices` APIs are just not supported on iOS browsers: [here they mention `getUserMedia`](http://stackoverflow.com/questions/42023882/how-to-use-getusermedia-on-ios-browsers), but the same seem to apply to `enumerateDevices`.
And as
> Firefox for iOS is just a wrapper of WebView just like all other browsers on iOS because Apple does not permit to use third-party browser engines on iOS. [[source](https://bugzilla.mozilla.org/show_bug.cgi?id=1224224#c1)]
it doesn't change much to use Firefox there :/

**Comment by maxlath** [comment]
The alternative would be to use an external app such as [zxing Barcode Scanner](https://play.google.com/store/apps/details?id=com.google.zxing.client.android) for Android, but none seem to fit. [Zxing themselves seem to have stopped working on iOS in 2014](http://stackoverflow.com/a/862656/3324977). The closest thing seem to be [ZBar](https://sourceforge.net/projects/zbar/), but, while it discussed it [[1](https://sourceforge.net/p/zbar/discussion/1072194/thread/058f48a4/)] [[2](https://sourceforge.net/p/zbar/discussion/1072194/thread/d4194618/)], no answer can be found on an existing [URL scheme to work with web apps](http://widequestion.com/question/zbar-url-scheme-to-get-scanned-information-back-to-web-page-iphone/) :/

**Comment by maxlath** [comment]
An other possible workaround: use image upload and [quagga static image analysis capability](https://github.com/serratus/quaggaJS#static-images) to scan barcodes: it would be a less fluid user experience with probably some trial and errors, but that's better than nothing I guess

**Comment by maxlath** [comment]
or we can just [wait for iOS to support it](http://caniuse.com/#feat=stream)

**Comment by maxlath** [comment]
iOS 11.2 supports `getUserMedia`, so we can consider it done, given everyone will progressively get there

**Comment by maxlath** [comment]
if we ever need an alternative to Quagga, there is that: [zxing-js](https://github.com/zxing-js/library)
