### ISSUE TITLE
user profile: buttons take too much space on small screen

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire-client#375]
step to reproduce: user must have a bio longer than the screen width (several lines)

![2022-12-21_15-15](https://user-images.githubusercontent.com/5363918/208925946-7818cc38-2ebc-499e-a718-00788b533a2d.png)

I dont normally open issues because of css bug, but when i do, its for the main page view (and because i could not easily spot the problem)

**Comment by maxlath** [comment]
could be addressed in #353

**Comment by jum-s** [comment]
done in #353
