### ISSUE TITLE
JSON parsing error when viewing the map of people who have a book

### ISSUE THREAD

**Issue by wetneb** [inventaire/inventaire-client#419]
Today I went to https://inventaire.io/entity/wd:Q52722355 (without being logged in)

and then I clicked on "Afficher sur la carte" to see if anyone has this book around me :)

I got the error message "JSON.parse: unexpected character at line 1 column 1 of the JSON data" and the map remains grey (uninitialized?).

## Screenshot 
![image](https://github.com/inventaire/inventaire-client/assets/309908/d924fb05-be73-48af-8e95-35808ac21ffd)

**Comment by maxlath** [comment]
ouch, thanks for reporting! Should have been fixed by c89cf1898
