### ISSUE TITLE
Too many unspecific “invalid label” errors when adding books

### ISSUE THREAD

**Issue by nclm** [inventaire/inventaire-client#424]
When scanning barcodes for books that are not yet in the database, Inventaire lets you add the title (either creating a new work or linking an existing work), which is great. However, more often than not, it leads to a unclear “invalid label” error after clicking on “Create selected books”. As a user, it is unclear what is wrong and what should I do and how to actually add the books then.

Example:
![Screenshot 2023-08-06 at 18-16-20 Import a collection - Inventaire](https://github.com/inventaire/inventaire-client/assets/923008/96e46f53-5993-4b6a-81cc-29e807d3d284)

**Comment by maxlath** [comment]
Thanks for reporting. This should now have been fixed by [898ce1e](https://github.com/inventaire/inventaire-client/commit/898ce1e7273d28269f4e3763906e6c9ee933cb9d), please re-open if that's not the case.
