### ISSUE TITLE
Overlapped pins on the map when already owning a copy of a book

### ISSUE THREAD

**Issue by nclm** [inventaire/inventaire-client#435]
If you have a book in your inventory and you display all available copies of this book on a map, there are two overlapped pins at your location: your profile + your book. In that particular case, there should only be one pin (maybe your book, since it has your profile picture too?).

<img width="199" alt="Screenshot 2023-09-07 at 10 00 37" src="https://github.com/inventaire/inventaire-client/assets/923008/944413f7-61b2-459f-80ff-e7397bb26601">

**Comment by jum-s** [comment]
Thanks for reporting. This should be fixed with 44d6b9112
Could you try and close the issue if it actually solved ?

**Comment by nclm** [comment]
Yes looks good now, thanks!
