### ISSUE TITLE
Untranslated string

### ISSUE THREAD

**Issue by lasconic** [inventaire/inventaire-client#440]
https://inventaire.io/add/import -> 2/ select the books you want to add 

This string is not translated and not translatable

See
https://github.com/inventaire/inventaire-client/blob/d4194de625483c0db78b0e4e176e229ea9ffe189/app/modules/inventory/components/importer/candidates_section.svelte#L17

**Comment by maxlath** [comment]
Indeed! Fixed by 4b13420 and https://github.com/inventaire/inventaire-i18n/commit/6e63f7600b1848eeb2ab5fb7b213b40d055adb0c
Thanks for reporting!
