### ISSUE TITLE
Cannot edit "original language" of a work

### ISSUE THREAD

**Issue by lasconic** [inventaire/inventaire-client#444]
* Go to https://inventaire.io/entity/inv:11ef050d78d5573f3b12c21c19e2f919/edit
* Scroll to Original Language 
* Click on "Add" 
* Enter the letter "c" or "f" and wait for the error message

 invalid types: languages (possible values: works, humans, genres, publishers, series, collections, genres, movements, users, groups, shelves, lists)

**Comment by lasconic** [comment]
Same for human entity

**Comment by jum-s** [comment]
Sorry for the inconvenience, this should be fixed now

**Comment by lasconic** [comment]
This is not fixed for me on inventaire.io

**Comment by lasconic** [comment]
At least, it was fixed, but now it's not working anymore

**Comment by jum-s** [comment]
Ah a reverted commit sneaked into main branch. Should be fixed now with bfd030711
