### ISSUE TITLE
Email validation confirmation dialog has json in the body 

### ISSUE THREAD

**Issue by shadow-identity** [inventaire/inventaire-client#484]
Reproduction: 
1. Create a new account
2. go to your mail box
3. find confirmation email
4. click [Confirm your email address] link
5. observe the bug:
![image](https://github.com/inventaire/inventaire-client/assets/1223112/e3a475c5-a874-4a90-a80a-cf22ef64719f)

**Comment by maxlath** [comment]
Indeed! I cleaned that up in 9fac6a754, thanks for reporting!

**Comment by shadow-identity** [comment]
Amazing! Thanks for instant reaction :)
