### ISSUE TITLE
Spurious error in login form

### ISSUE THREAD

**Issue by wetneb** [inventaire/inventaire-client#486]
Hello hello! A funny easter egg for you :)

Here is how to find it:
* while logged out, go to https://inventaire.io/login
* click in the password field to focus it
* click somewhere else to unfocus it

Underneath the password field, you will see: `e is undefined` (with Firefox) or `Cannot read properties of undefined (reading 'length')` (with Chromium).

![image](https://github.com/inventaire/inventaire-client/assets/309908/5b25b9eb-c11c-4e55-ac4a-ba25ae8698e0)

**Comment by maxlath** [comment]
Not the nicest error message indeed :sweat_smile: That should have been fixed by 8255b57c1, thanks for reporting! Happy egg hunt day to those who celebrate :rabbit: :stuck_out_tongue_winking_eye:
