### ISSUE TITLE
Cannot set map position

### ISSUE THREAD

**Issue by oliverpool** [inventaire/inventaire-client#487]
Hello,

while logged-in, if I:
- visit https://inventaire.io/users/public 
- click on `Edit your position`
- Set a city in the `Location field` (Paris for instance)
- and type `Enter`

I get
```
undefined has no properties
```

![image](https://github.com/inventaire/inventaire-client/assets/3864879/7dc596e6-06a5-4eec-928d-b1a836cbde1a)

The console log indicates
```
TypeError: undefined has no properties
    i nominatim.js:14
[loggers.js:55:10](webpack://inventaire-client/app/lib/loggers.js)
    i loggers.js:55
    update flash.svelte:22
    De scheduler.js:111
    Te scheduler.js:75
    n await_block.js:55
    Ke await_block.js:66
```

However I think the line numbers are not correct, because line 14 of `nominatim.js` is actually executed (the https://nominatim.openstreetmap.org/search?q=Paris&format=json&accept-language=en request is successfully sent).

**Comment by maxlath** [comment]
Thanks for reporting! That should now have been fixed by e5edb7e8a, please re-open the issue if that's still not working for you
