### ISSUE TITLE
Imprecise dates of birth are misleading

### ISSUE THREAD

**Issue by jum-s** [inventaire/inventaire-client#512]
20th century precision cannot be simplified to 2000

[This person](https://www.wikidata.org/wiki/Q61718357) is most likely not in their twenties:

![2024-10-06_15-55](https://github.com/user-attachments/assets/f1379e37-249b-4fdd-84f7-a74701481f90)

Some examples are available with [this query](https://query.wikidata.org/#SELECT%20%3Fperson%0AWHERE%0A%7B%0A%20%20%3Fperson%20wdt%3AP31%20wd%3AQ5%3B%0A%20%20%20%20%20%20%20%20%20%20p%3AP569%2Fpsv%3AP569%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AtimePrecision%20%3Fprecision%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20wikibase%3AtimeValue%20%3Fdate%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5D%20.%0A%20%20FILTER%28%20%3Fprecision%20%3E%3D%20%227%22%5E%5Exsd%3Ainteger%20%29%20%23%20precision%20of%20at%20least%20century%0A%7D%0ALIMIT%201000)

Fortunately, `wikidata-sdk` is already returning unsimplified claims with a time precision. Then, unprecise data value could be dropped in `formatClaims()` with something that could look like: 

```js
if (allowlistedClaims.P569.mainsnak.datavalue.value.precision < 9) {
 delete simplifiedClaims.P569
}
```

**Comment by maxlath** [comment]
That should probably be done directly in `wikidata-sdk` when `timeConverter = 'simple-day'` is used
