### ISSUE TITLE
variable dimensions of group pictures makes group icon being displayed inconsistently

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire-client#62]
example:
![group_icon](https://cloud.githubusercontent.com/assets/1596934/13323535/38c877f8-dbda-11e5-9826-8300fbb5beaa.png)

possible solution:
- set group picture as icon background with a fixed height and [`background-size` set to `cover` or `contain`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size) attribute so that it takes a constant width and height

**Comment by AditSaxena** [comment]
Hi
I would like to work on this issue

**Comment by maxlath** [comment]
Hi @AditSaxena, it seems that it had already been solved by bfc7b98d61 but that we forgot to close the issue, sorry :sweat_smile:
