### ISSUE TITLE
improve css cross browser support

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire-client#88]
Despite the use of [postcss](https://github.com/postcss/postcss) with [autoprefixer](https://github.com/postcss/autoprefixer) ([see brunch-config](https://github.com/inventaire/inventaire-client/blob/943fe11140ade7a0f966aebbc9097d9d974e3cf8/brunch-config.coffee#L49-L52)), cross browser support could be greatly improved to say the least.

* this is the [home page](http://inventaire.io/welcome) in Firefox/Ubuntu 16.04 (the browser I use and thus the one I test the most):
![inv-firefox](https://cloud.githubusercontent.com/assets/1596934/20677881/f36c9f46-b594-11e6-84da-302c63801a3b.png)

* this is the same page in Edge/Windows 10
![inv-windows](https://cloud.githubusercontent.com/assets/1596934/20677871/e6ca4572-b594-11e6-9d70-7aea8631d2d5.png)

Any help to address those issues is super extra welcome! :heart:  :heart:  :heart:

**Comment by Abbe98** [comment]
I can't reproduce the bug displayed above with Edge or IE10. Instead the column expands to over 100% of the window:
![image](https://cloud.githubusercontent.com/assets/2631719/20681683/f075ebd4-b5a4-11e6-9fc1-605b59745d4a.png)

Other  homepage bug appearing in both Edge and IE10:
![image](https://cloud.githubusercontent.com/assets/2631719/20681665/df987b88-b5a4-11e6-8b0e-8ca1a9431a33.png)

**Comment by maxlath** [comment]
thank you for reporting!
wow, how can Edge render so differently from Firefox? oO
For the [landing screen](https://github.com/inventaire/inventaire-client/blob/master/app/modules/welcome/views/templates/landing_screen.hbs) (the upper part), I suspect a different handling of `display:flex`, I have seen comparable issues on Safari but I thought those issues were over

**Comment by maxlath** [comment]
great resources to find support issues on inventaire: [doiuse.com](http://www.doiuse.com/?url=https%3A%2F%2Finventaire.io%2F&browsers=&css=)

**Comment by maxlath** [comment]
closing this issue as it isn't specific enough
