### ISSUE TITLE
add advanced search

### ISSUE THREAD

**Issue by maxlath** [inventaire/inventaire-client#9]
add a menu to search with named fields:
- title
- author
- isbn (re-use existant per-isbn search)

**Comment by JR-Utily** [comment]
+1
This feature is a must have to be able to fill a big collection from scratch.
I don't know if it is directly related to this issue or not, as I don't know the structure of your DB, but IMHO, books should be indexed (and searchable) by Authors, Publishers and Titles to be easy to find back.

**Comment by maxlath** [comment]
Done some years ago, forgot to close the issue ^^'
