### ISSUE TITLE
How to add a cover?

### ISSUE THREAD

**Issue by thewholelifetolearn** [inventaire/inventaire-client#97]
I have some books that don't have a cover (https://inventaire.io/entity/inv:9cf5fbb9affab552cd4fb77712a074db or https://inventaire.io/entity/inv:6931b48d3cdd5b6ec0383917cb634125).

How can I add a cover to those books? I don't see a form or anything else that helps to do that

**Comment by maxlath** [comment]
There was one, then we lost this feature while deploying the new entities system a few months ago, and I'm currently working on integrating it to the [entity edition interface](https://inventaire.io/entity/inv:9cf5fbb9affab552cd4fb77712a074db/edit) :)

**Comment by maxlath** [comment]
it's online \o/

**Comment by thewholelifetolearn** [comment]
Thanks. I have tried it and it works well 👍
